version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://laptop-price-backend-dxdhgtgkcthydqa4.centralus-01.azurewebsites.net # Use the Azure backend URL
