version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" # Local Flask backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Local Next.js frontend (port 3000)
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://laptop-price-backend-dxdhgtgkcthydqa4.centralus-01.azurewebsites.net # Azure backend URL
    depends_on:
      - backend
