name: Deploy Full Stack App

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'  # Trigger on backend changes
      - 'frontend/**' # Trigger on frontend changes

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: flasknextjsapp.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t flasknextjsapp.azurecr.io/laptop-price-backend:latest ./backend
          docker push flasknextjsapp.azurecr.io/laptop-price-backend:latest

      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: laptop-price-backend  # Your Azure backend app name
          images: flasknextjsapp.azurecr.io/laptop-price-backend:latest

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend  # Deploy frontend after backend succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: flasknextjsapp.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t flasknextjsapp.azurecr.io/laptop-price-frontend:latest ./frontend
          docker push flasknextjsapp.azurecr.io/laptop-price-frontend:latest

      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: laptop-price-frontend  # Your Azure frontend app name
          images: flasknextjsapp.azurecr.io/laptop-price-frontend:latest